### PR TITLE
Increase the maximum password length

### LINKED ISSUE #1921: Increase the maximum password length
The passwords are limited to 40 characters.
I don't like the limit, so is it possible to increase it?

### PR DESCRIPTION
**Pull request by SuperNascher**
This resolves #1921

### CODE REVIEW

**Comment by dnrce** [comment]
lenght

**Comment by dnrce** [comment]
I know there is at least one test that will need to be updated.

**Comment by dnrce** [comment]
Also, can you please adjust the commit message to make it clear that this only the _maximum_ length being adjusted? "Increase the maximum password length", for example.

**Comment by SuperNascher** [comment]
Ok

**Comment by dnrce** [comment]
It looks like `test_validate_long_password` is the only failing test. Please update https://github.com/TracksApp/tracks/blob/9a18705f70eafc6ac442713203e8b25d7285d61d/test/models/user_test.rb#L47-L48.

**Comment by dnrce** [comment]
Actually, it probably makes sense to limit the length to 72 characters. Bcrypt ignores anything after 72. See Devise: https://github.com/plataformatec/devise/commit/c7cc91cb65687e0325d817472a9da9b0c3894b41

**Comment by SuperNascher** [comment]
I have set the maximum length to 72 characters on both files.

**Comment by dnrce** [comment]
:thumbsup: Awesome. Thanks!!

**Pull request merged**
