### PR TITLE
A more rational way to load the text input with the previous names

### PR DESCRIPTION
**Pull request by RyanTruran**
I moved the changes that I originally made on the jeditable plugin to the track.js.erb file.

### CODE REVIEW

**Comment by mattr-** [comment]
Cool! Thanks!

This is looking good to me. Do you mind if I squash this down into a single commit when I merge it?

**Comment by RyanTruran** [comment]
Is their some way that I can do that?

**Comment by mattr-** [comment]
The way that I do it is in cases like yours would be an interactive rebase (see the section `Squashing commits` from [the Git book](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)) with a force push (`git push -f`) to your repo. GitHub will automatically update the PR here once you've done both of those things.

**Comment by RyanTruran** [comment]
Awesome thanks.

**Comment by RyanTruran** [comment]
I may have messed it up. Do you mind looking at it.

**Comment by mattr-** [comment]
The last commit looks fine but the first two commits aren't needed.  Any chance that you could remove those? We should be good after that.

**Comment by RyanTruran** [comment]
Is that through rebase / drop

**Comment by mattr-** [comment]
> Is that through rebase / drop

Yup. 😃

**Comment by RyanTruran** [comment]
Done

**Comment by mattr-** [comment]
:thumbsup:

**Comment by mattr-** [comment]
Thanks for this contribution!! 

bitmoji

**Pull request merged**
