### PR TITLE
repeating -> recurring, repeat -> recurrence

### PR DESCRIPTION
**Pull request by C-Otto**

### CODE REVIEW

**Comment by dnrce** [comment]
You're correct that "repeating" becomes "recurring", but "repeat" should become "recurrence", as in `MonthlyRecurrencePatternTest`.

**Comment by C-Otto** [comment]
Done.

**Comment by dnrce** [comment]
Great. Nice cleanup!

**Comment by lrbalt** [comment]
Hmm, too late again :-) 

There was a discussion on the mailing list at the time I added recurring todos where using repeat pattern / repeating todos was deemed better than recurring todos. I never got around to renaming it all to repeat pattern...

Anyway, better to be consistent :-)

**Pull request merged**
