### PR TITLE
Fix 2277: Adapt migration script for PostgreSQL

### LINKED ISSUE #2277: Failed db migration (tags)
I'm on master and get this:

```
# bundle exec rake db:migrate RAILS_ENV=production
(in /home/cotto/git/tracks)
== 20190618202817 AddUserIdToTag: migrating ===================================
-- add_column(:tags, :user_id, :integer)
   -> 0.0440s
-- execute("      SELECT t.id AS tid, tds.user_id AS todo_uid, rt.user_id AS rtodo_uid\n      FROM tags t\n      JOIN taggings tgs ON tgs.tag_id = t.id\n      LEFT OUTER JOIN todos tds\n       ON tgs.taggable_type = \"Todo\" AND tds.id = tgs.taggable_id\n      LEFT OUTER JOIN recurring_todos rt\n       ON tgs.taggable_type = \"RecurringTodo\" AND rt.id = tgs.taggable_id\n      WHERE rt.id IS NOT NULL OR tds.id IS NOT NULL\n      GROUP BY t.id, tds.user_id, rt.user_id\n")
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedColumn: ERROR:  column "Todo" does not exist
LINE 5:        ON tgs.taggable_type = "Todo" AND tds.id = tgs.taggab...
                                      ^
:       SELECT t.id AS tid, tds.user_id AS todo_uid, rt.user_id AS rtodo_uid
      FROM tags t
      JOIN taggings tgs ON tgs.tag_id = t.id
      LEFT OUTER JOIN todos tds
       ON tgs.taggable_type = "Todo" AND tds.id = tgs.taggable_id
      LEFT OUTER JOIN recurring_todos rt
       ON tgs.taggable_type = "RecurringTodo" AND rt.id = tgs.taggable_id
      WHERE rt.id IS NOT NULL OR tds.id IS NOT NULL
      GROUP BY t.id, tds.user_id, rt.user_id

```

### PR DESCRIPTION
**Pull request by C-Otto**
replace " by '
use row['colname'] instead of row[n]

fixes #2277

### CODE REVIEW

**Comment by C-Otto** [comment]
I don't know if this works for other SQLs, though :)

**Comment by mattr-** [comment]
It passed CI, so I'm inclined to think that it does. I'll do some testing later to find out for sure.

**Comment by ZeiP** [comment]
Does CI run the migrations at all, or does it just initialise a fresh database from the most recent schema?

**Comment by mattr-** [comment]
It's a fresh database, which I realized only after I started looking at the
build output.

>

**Comment by mattr-** [comment]
Migrations ran on MySQL without any syntax errors, so I'm just going to merge this.

**Pull request merged**
