### PR TITLE
Update the navbar design

### LINKED ISSUE #1952: master: top bar hides top content
If the browser window is too narrow, the black top bar wraps and increases in height. This hides the topmost context in my case.

### PR DESCRIPTION
**Pull request by dnrce**
This isn't a complete overhaul, but it condenses the navbar a bit and makes it break smoothly as the window is resized. This should fix #1952.

screen shot 2016-02-14 at 10 16 58 pm

screen shot 2016-02-14 at 22 14 59
screen shot 2016-02-14 at 22 15 36
screen shot 2016-02-14 at 22 15 49

### CODE REVIEW

**Comment by dnrce** [comment]
This has probably broken some acceptance tests -- I honestly haven't run the suite but I'll see what Travis flags.

**Comment by dnrce** [comment]
Still working on the tests. I'd like to rebase this on top of #1995 and #1996 once they're merged.

**Comment by dnrce** [comment]
I'm removing the "DO NOT MERGE" tag here. There are five remaining Cucumber failures, all of which are present in the current build of master (a big improvement over the 180 failures there).

Thoughts on the design? Doesn't have to be final, but is it a positive step?

**Comment by C-Otto** [comment]
I like it

**Comment by dnrce** [comment]
Thanks @C-Otto. @mattr-, thoughts?

**Comment by mattr-** [comment]
Yup. I'm for it. Merging.

**Pull request merged**
