### PR TITLE
Increase the usability of the new todo mobile view

### PR DESCRIPTION
**Pull request by mattr-**
Entering new todos is somewhat painful. This set of changes increases the usability of the new todo mobile UI by enlarging elements to make them easier to hit.

Here's a screenshot of what these changes look like on a phone:

ios simulator screen shot jul 24 2015 10 42 25 pm

### CODE REVIEW

**Comment by mattr-** [comment]
ugh. not sure that hound is a good idea. except for the new stuff that it points out, I followed the existing style everywhere else. :unamused:

**Comment by mattr-** [comment]
Also, the code climate check seems less effective, since I can't actually click 'Details' to see what's going on and why code climate seems to have found 157 new issues. :fearful:

**Comment by dnrce** [comment]
Yeah, this is the first PR opened since I enabled it as an experiment. I'll turn it back off until it's more configured.

Code Climate is not an addition, but it's now exposed through the GitHub UI.

**Comment by mattr-** [comment]
I fixed the indentation in the file and a few of the issues that Hound pointed out. Let me know if there's anything else that I should address in this PR. :smiley:

**Comment by mattr-** [comment]
I've got some larger mobile changes in the works and I'd like to clear this PR out before I submit those for PR. Is there anything else I need to do or can I go ahead and merge this? :smiley:

**Comment by mattr-** [comment]
Yay mobile improvements! :shipit:

**Pull request merged**
