### PR TITLE
use @not_done_todos for feeds

### LINKED ISSUE #1726: Per-project/context RSS/iCal feeds show all todos
This is the return of #1684, except text feeds are working. I can reproduce this on trunk by creating three tasks with three different projects, and requesting the feed for one project.

### PR DESCRIPTION
**Pull request by C-Otto**
fixes #1726

the name @not_done_todos is wrong and should be replaced in a dedicated fix

**Note that this targets the 2.3 branch**

### CODE REVIEW

**Comment by dnrce** [comment]
Thanks! I guess there are no tests for these feeds? It would be nice to add coverage before closing the bug.

**Comment by C-Otto** [comment]
I added some tests. Feel free to teach me how to get rid of redundancy here, parameterized tests would be nice.

**Comment by C-Otto** [comment]
I guess the CI tests were failing even before these changes?

**Comment by mattr-** [comment]
:boom: thanks for fixing!

Sorry for taking so long to get this merged.

**Pull request merged**
