### PR TITLE
Sort by date in calendar.

### PR DESCRIPTION
**Pull request by fusionat**
Sort by date in calendar #1727, test pass

### CODE REVIEW

**Comment by fusionat** [comment]
I fixed it. enjoy!

**Comment by C-Otto** [comment]
Is there a reason not to merge this?

**Comment by fusionat** [comment]
yes. Need test

**Comment by C-Otto** [comment]
I don't see anything your change fixes. And it seems you confused the calendar (your change) and the tickler (mentioned in #1727). Could you check that you really did what you wanted to do? Can you give an example of a situation where your change helps?

**Comment by C-Otto** [comment]
I think #1805 solves the issue, please close this pull request.

**Pull request closed without merging**
