### PR TITLE
Default project should be empty

### PR DESCRIPTION
**Pull request by matjack1**
I think there's been a merge conflict in the last batch and this has been overridden. It's re-fixing a recent fix :)

### CODE REVIEW

**Comment by C-Otto** [comment]
Thank you!

**Comment by dnrce** [comment]
Thanks! Can you add a test here?

**Comment by mattr-** [comment]
My fault. Sorry. A test would definitely be good. @matjack1 is that something you think you could do soon?

**Comment by matjack1** [comment]
Yes @dnrce and @mattr- I've just repushed the commit with a new test. I searched for an existing step definition that would be suitable for my test but I couldn't find it. If you have any suggestions they are welcome.
The test correctly fails without the fix, hope it's good :)

**Comment by matjack1** [comment]
I don't get why the functional tests were failing. I've repushed to try again. I've Ruby 2.2 on my machine but I can't replicate the bug that was showing up in Travis. Let's see.

**Comment by matjack1** [comment]
Can you have a look at this again? I just repushed on Travis, what do you think?

**Comment by mattr-** [comment]
Yeah, we'll take a look at this soon.

**Comment by mattr-** [comment]
Looks good to me. Thanks @matjack1!

**Pull request merged**
