### PR TITLE
enable caching of gems on travis

### PR DESCRIPTION
**Pull request by lrbalt**
as described in http://docs.travis-ci.com/user/caching/

### CODE REVIEW

**Comment by mattr-** [comment]
We're on the container based infrastructure now, correct? If so, :+1:

**Comment by lrbalt** [comment]
the failures are cucumber timeouts (again!). It seems ok to merge

**Comment by lrbalt** [comment]
yes, we are on container based infrastructure

**Comment by mattr-** [comment]
:heart: me some caching. Thanks!

**Pull request merged**
