### PR TITLE
Add Rails version to the migrations.

### PR DESCRIPTION
**Pull request by srbaker**
Got the complaint mentioned in #2170.

With this, both of the issues mentioned there are addressed.

### CODE REVIEW

**Comment by mattr-** [comment]
I'm conflicted about this. On the one hand, this is the right thing to do to fix these migrations. On the other, all of them are so old, I'm not sure it makes sense to keep them. Folks can (and should, really) do a `bin/rake db:schema:load` instead of running migrations at first install. Let me think about it for a bit longer.

**Comment by srbaker** [comment]
The reason I need the migrations is because Rails started adding database-specific stuff to `schema.rb`, so I can't db:schema:load on Postgres or SQLite3, even though the app works fine with both.

Any other ideas?

**Comment by mattr-** [comment]
I was considering only supporting MySQL for Tracks going forward, since there are features that only work properly with MySQL. That is one route we could take.

I think I'll just merge this for now, and then open another issue for the database support discussion.

**Comment by srbaker** [comment]
Thanks!

I'm hoping to launch a service based on this, using Postgres. I'd love to work on those features, well abstracted, so I can use Postgres. I'm looking forward to the discussion either way. :D

**Comment by C-Otto** [comment]
I'm using PostgreSQL and like to keep it that way

**Pull request merged**
