### PR TITLE
when recurring todos always use midnight for "show from"

### LINKED ISSUE #1940: Deferred action with "Show Today"
I have a recurring todo which is supposed to be shown today. Indeed, I see it in the tickler/deferred view/... with a box containing "Show Today". Why isn't that shown right now?

The `show_from` column contains `2015-11-21 20:55:22.2137`, which is in a few hours. I guess the H:M:s part of recurring todos should be set to midnight (or treated as such?).

### PR DESCRIPTION
**Pull request by C-Otto**
fixes #1940

### CODE REVIEW

**Comment by mattr-** [comment]
Does this need to go to the 2.3 branch as well?

**Comment by C-Otto** [comment]
I will investigate.

**Comment by mattr-** [comment]
If this does need to go to the 2.3 branch, it'll have to be modified as the current patch doesn't apply cleanly. I think we'll just leave this as a 2.4 thing for now.

**Comment by C-Otto** [comment]
Cherry-picking worked just fine, see #1948

**Comment by C-Otto** [comment]
This only works for recurring todos with a "show from" setting, not a "due date". I'll fix.

**Pull request closed without merging**
