### PR TITLE
Change the Flash charts to Charts.js

### PR DESCRIPTION
**Pull request by ZeiP**
This should show exactly the same charts as the old Flash charts (except for the appearance, of course).

### CODE REVIEW

**Comment by ZeiP** [comment]
@mattr-, the Codeclimate issues (length and amount of methods) are the same that have previously existed in the controller file. Should these be fixed before merging or could we merge this in to get the charts working?

**Comment by mattr-** [comment]
Nah, we can ignore those. I'll probably just turn codeclimate off for now.

**Comment by mattr-** [comment]
:tada:

**Comment by C-Otto** [comment]
```
stats:195 Uncaught ReferenceError: Chart is not defined
    at initChart (stats:195)
```

I don't see any graphs on my page

**Comment by ZeiP** [comment]
@C-Otto, weird. I'll try to reproduce this. Thanks for reporting!

**Pull request merged**
