### PR TITLE
Avoid using %i, which requires Ruby 2.0

### LINKED ISSUE #1997: Error in Ruby 1.9.3 with updated preferences page
The `PreferencesControllerTest#test_index_sets_prefs_and_user` is failing in Ruby 1.9.3 only, as of 7652791451959a6433a1906a215d5600c4db30f3 (#1974).

```
$ bin/rake test test/controllers/preferences_controller_test.rb test_index_sets_prefs_and_user
Run options: -n test_index_sets_prefs_and_user --seed 19003

# Running:

E

Finished in 0.655737s, 1.5250 runs/s, 0.0000 assertions/s.

  1) Error:
PreferencesControllerTest#test_index_sets_prefs_and_user:
SyntaxError: ~/src/tracks/app/views/preferences/_date_and_time.html.erb:7: unknown type of %string
'.freeze;   %i{default short long longer}.each do |format|
               ^
~/src/tracks/app/views/preferences/_date_and_time.html.erb:7: syntax error, unexpected $end, expecting keyword_end
'.freeze;   %i{default short long longer}.each do |format|
               ^
    app/views/preferences/index.html.erb:28:in `block in _app_views_preferences_index_html_erb__1336127631248805532_70356743837640'
    app/views/preferences/index.html.erb:10:in `_app_views_preferences_index_html_erb__1336127631248805532_70356743837640'
    test/controllers/preferences_controller_test.rb:29:in `block in <class:PreferencesControllerTest>'

1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

### PR DESCRIPTION
**Pull request by dnrce**
Fixes #1997

This should turn the 1.9.3 "lite" (i.e. SQLite) build green.

### CODE REVIEW

**Comment by mattr-** [comment]
Any reason why we still want to support anything that's not 2.1 or later?

**Comment by dnrce** [comment]
Because our current version of Rails does. If this is the only thing, why wouldn't we? I'll be happy to drop <2.2 support once we're on Rails 5.

**Comment by mattr-** [comment]
Ruby 1.9.3 has been end-of-lifed and is no longer supported. I don't agree with supporting a Ruby version that has reached EOL just because Rails does. Can we drop support for 1.9.3 on master and only support Ruby >= 2.0?

**Comment by C-Otto** [comment]
Debian Oldstable (Wheezy) has 1.9.3 as far as I know. I'm running Stable (Jessie), but I don't know who still uses Oldstable.

**Comment by dnrce** [comment]
I agree that supporting old Rubies isn't worth effort, but AFAIK so far that "effort" is literally only this PR. I can't think of a single instance where use of 1.9.3 or 2.0.0 has been the cause of a help question, either.

**Comment by mattr-** [comment]
:+1:

**Pull request merged**
