### PR TITLE
Redesign the login page

### PR DESCRIPTION
**Pull request by mattr-**
Makes use of both bootstrap and a rendering of the Tracks logo to provide a bit better experience in term of brand identity as well as also supporting mobile better.

There are a few things left to do here before this gets merged, but I wanted to provide something for feedback, since this is a large departure from our previous login page:

 - [x] Fix the flash rendering to use bootstrap styles and be colored (it's currently unstyled)
 - [x] Remove the use of flexbox for better browser support (Firefox and IE8+)
 - [x] Verify the cucumber scenarios aren't broken. Fix them if they are.
 - [x] Double check rendering on IE 8+
 - [x] Fix Safari 7 rendering issue
 - [x] Check IE 10 rendering
 - [x] Check IE 11 rendering

### Desktop (Chrome on OS X)
Desktop - Chrome on OS X

### Nexus 5 Emulation with Chrome
Nexus 5 Emulation with Chrome

### iPad Emulation with Chrome
iPad Emulation with Chrome

### CODE REVIEW

**Comment by mattr-** [comment]
I discovered that CSS gradients aren't supported in IE until version 10. IE8 and IE9 users account for approximately 2% of the global user base. Are we ok with dropping support for those browsers in version 2.4?

**Comment by dnrce** [comment]
Sharp!

How does IE degrade?

Some thoughts:

My feeling is that Tracks should move away from the "10" logo, because I don't think it makes much sense, and toward the check mark instead.

I don't know whether this shadowed raised panel styling will be consistent with any UI elements in the actual app.

I had been thinking we might even want to do away with a separate login layout in the move to Bootstrap.

**Comment by mattr-** [comment]
>How does IE degrade?

:laughing: Not well. I'll pull screenshots from the VM and post them tomorrow.

> My feeling is that Tracks should move away from the "10" logo, because I don't think it makes much sense, and toward the check mark instead.

I'm cool with that. I was mostly trying to reuse the existing branding rather than try to come up with something new.

> I had been thinking we might even want to do away with a separate login layout in the move to Bootstrap.

I will admit to thinking about that for a minute and then deciding that I would try to make the most minimal amount of change possible. I'm sure it can be done. I think it's a great idea. I just didn't do it as part of this PR.

**Comment by mattr-** [comment]
Here's IE 8:
new login ie8

Here's IE 9:
new login ie9

**Comment by dnrce** [comment]
Ha! Go, IE.

I guess I didn't answer your question directly before but I'm totally happy with dropping IE8 & 9 support. Users will still have Tracks 2.3 available to them.

**Comment by mattr-** [comment]
:+1: Cool.

**Comment by mattr-** [comment]
I intend to squash this into a better story commit wise once it's good to go, just putting the individual commits here so that it's easier to review as I make changes.

**Comment by mattr-** [comment]
Also, IE 10 and IE 11 both look fine:

IE 10:
screen shot 2015-12-13 at 7 49 04 pm


IE 11:
screen shot 2015-12-13 at 7 52 11 pm

**Comment by mattr-** [comment]
:boom: All done. I think. Here's a screenshot with the flash styled properly.

screen shot 2015-12-15 at 8 03 34 pm

**Comment by mattr-** [comment]
I can't reproduce the cucumber test failures locally by either running the scenario that's failing by itself or the whole cucumber suite all together (well, at least what's completed so far). I think i'll wait for the full suite to finish on my machine and if it does so without errors, go ahead and merge this.

**Comment by mattr-** [comment]
got an error with the tagging todos completely unrelated to anything this changes. Merging.

**Comment by C-Otto** [comment]
Please have a look at issue #1954

**Pull request merged**
