### PR TITLE
fix #1754

### LINKED ISSUE #1754: Cyclic dependency
I created a few new tasks in a fresh project and then connected those using drag-n-drop. By accident, I created a dependency of taskA to taskB, although I created the reverse dependency just before that. I remember seeing some red error message flash up (which I ignored/did not read). I assumed the dependency was not added, as it would create a cycle.

However, according to my database, there is the cyclic dependency:

```
tracks=# select * from dependencies where successor_id in (5063,5064);
  id  | successor_id | predecessor_id | relationship_type 
------+--------------+----------------+-------------------
 1098 |         5064 |           5063 | 
 1099 |         5063 |           5064 | 
```

Running with PostgreSQL and on f81efebd8ce18bbca9abd567d345edbc22e80061.

### PR DESCRIPTION
**Pull request by C-Otto**
Move the validation to 'Dependencies', fix test case

### CODE REVIEW

**Comment by C-Otto** [comment]
This changes the error message, as the GUI code only checks if the task can be saved. The exception now thrown is not handled.

**Comment by C-Otto** [comment]
Now the error message should be the same (at least in my manual tests), but I'm not too happy with the code. If you manage to create a cleaner version, feel free to enlighten me :)

**Comment by C-Otto** [comment]
When trying to create the cyclic dependency, the todo is removed from the view. Instead, when the error message is shown, the UI should stay as it was before.

**Comment by lrbalt** [comment]
thanks!

**Comment by dnrce** [comment]
This should have been done against 2.3_branch then merged down to master. I'll cherry-pick it.

**Comment by C-Otto** [comment]
I think the UI feedback is still wrong, as indicated in my last comment.

**Comment by dnrce** [comment]
Do you think this should not have been merged?

**Comment by C-Otto** [comment]
I'll check (today).

**Comment by C-Otto** [comment]
When using drag and drop, the dragged action (closing the cycle if added as a successor) disappears.
When using the 'edit' menu, no error is shown, and the popup cannot be closed using 'Update'.

**Pull request merged**
