### PR TITLE
Fix recurring todo dialogs

### PR DESCRIPTION
**Pull request by dnrce**
* Position the dialog below the navbar
* Make sure the edit form is placed inside `.legacy-ui` in the DOM

### CODE REVIEW

**Comment by C-Otto** [comment]
Looks good, although I see a big gray box between the last item ("set the date") and the buttons ("update", "cancel").

**Comment by dnrce** [comment]
True, but it's present in 2.3.

**Comment by dnrce** [comment]
Well, it's not gray in 2.3, it's yellow. But the spacing is unchanged.

**Comment by dnrce** [comment]
My goal in this PR is only to fix the real usability problems. I expect this form to get some updates as we continue to work through the UI redesign.

**Comment by dnrce** [comment]
That all being said, I just added a CSS rule to remove the gray background. It doesn't fix the spacing, but does it make it less obnoxious?

**Comment by C-Otto** [comment]
Yeah, that's better. But I agree, some other issues need to be tackled with higher priority :)

**Comment by mattr-** [comment]
:tada: good stuff

**Pull request merged**
