### PR TITLE
Show links to context/project also for completed actions

### LINKED ISSUE #1840: GUI enhancement: add links to "completed actions" list
The "completed actions" list shows the project and context of each completed action (depending on the current view), but this information is not clickable. Adding links, similar to the list of active/pending actions with square brackets?, would be useful.

### PR DESCRIPTION
**Pull request by C-Otto**
Fix #1840

### CODE REVIEW

**Comment by dnrce** [comment]
Does this change mean the context name is no longer displayed in full for completed actions? I think that would be a loss of functionality.

**Comment by C-Otto** [comment]
If the verbose option is not set, you just see [P] and [C]. You'd need to hover over it (or click) to see the project name/context name. If the verbose option is set, you see it.

Personally, I'm very interested in this information, and with the verbose option set I'm fine with the solution.

**Comment by C-Otto** [comment]
This is how it looks like now: http://imgur.com/olA9yHJ,eAp4uYC#0

**Comment by mattr-** [comment]
I was missing this just the other day! Thanks! :heart:

**Pull request merged**
